name: Trigger twitter deleter using a CRON job 
on:
  schedule:
    # Runs at the end of the year
    - cron: '59 11 31 12 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip # Cache previous environment if no change on requirements
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          API_KEY: ${{secrets.API_KEY}}
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: python3 purge_tweets.py



