name: purge-tweets
on:
  schedule:
    # Runs at the end of the year
    - cron: '00 12 01 01 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: pip # Cache previous environment if no change on requirements
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute script
        env:
          API_KEY: ${{secrets.API_KEY}}
          API_KEY_SECRET: ${{secrets.API_KEY_SECRET}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
        run: |
          python3 purge_tweets.py
          python3 plot.py

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: './backups/*'
          default_author: 'github_actions'
